[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "https://findlipfillers.com/*"
  to = "https://www.findlipfillers.com/:splat"
  status = 301
  force = true